### ISSUE TITLE
`Alloc` trait removed in 1.43 nightlies

### ISSUE THREAD

**Issue by rubdos** [drone-os/libcore-drone#1]
We just tried building a test-application with `1.43.0-nightly`, 2020-02-05, and it seems like `core::alloc::Alloc` got removed. Cfr. https://github.com/rust-lang/rust/issues/32838 and the [new `core::alloc` nightly documentation](https://doc.rust-lang.org/nightly/core/alloc/index.html).

I am not experienced enough with custom allocators in Rust to fix this myself, and I don't really find what it was replaced with, so I'm just letting you know. Cc @vanarill

**Comment by valff** [comment]
Thanks for the report. This will be fixed soon in the new Drone 0.12 release.
